# tag: posix
# mode: compile

# This file is generated by `Tools/gen_tests_for_posix_pxds.py`.

use posix

use posix::dlfcn
use posix::dlfcn
use posix::dlfcn::*

use posix::fcntl
use posix::fcntl
use posix::fcntl::*

use posix::ioctl
use posix::ioctl
use posix::ioctl::*

use posix::mman
use posix::mman
use posix::mman::*

use posix::resource
use posix::resource
use posix::resource::*

use posix::select
use posix::select
use posix::select::*

use posix::signal
use posix::signal
use posix::signal::*

use posix::stat
use posix::stat
use posix::stat::*

use posix::stdio
use posix::stdio
use posix::stdio::*

use posix::stdlib
use posix::stdlib
use posix::stdlib::*

use posix::strings
use posix::strings
use posix::strings::*

use posix::time
use posix::time
use posix::time::*

use posix::types
use posix::types
use posix::types::*

use posix::uio
use posix::uio
use posix::uio::*

use posix::unistd
use posix::unistd
use posix::unistd::*

use posix::wait
use posix::wait
use posix::wait::*
