# tag: posix
# mode: compile

# This file is generated by `Tools/gen_tests_for_posix_pxds.py`.

use posix

use posix.dlfcn
from posix cimport dlfcn
from posix.dlfcn cimport *

use posix.fcntl
from posix cimport fcntl
from posix.fcntl cimport *

use posix.ioctl
from posix cimport ioctl
from posix.ioctl cimport *

use posix.mman
from posix cimport mman
from posix.mman cimport *

use posix.resource
from posix cimport resource
from posix.resource cimport *

use posix.select
from posix cimport select
from posix.select cimport *

use posix.signal
from posix cimport signal
from posix.signal cimport *

use posix.stat
from posix cimport stat
from posix.stat cimport *

use posix.stdio
from posix cimport stdio
from posix.stdio cimport *

use posix.stdlib
from posix cimport stdlib
from posix.stdlib cimport *

use posix.strings
from posix cimport strings
from posix.strings cimport *

use posix.time
from posix cimport time
from posix.time cimport *

use posix.types
from posix cimport types
from posix.types cimport *

use posix.uio
from posix cimport uio
from posix.uio cimport *

use posix.unistd
from posix cimport unistd
from posix.unistd cimport *

use posix.wait
from posix cimport wait
from posix.wait cimport *
